{{- if not .Values.sentry.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-secret
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  key: {{ randAlphaNum 50 | b64enc | quote }}
{{- end -}}