---
apiVersion: v1
items:
- apiVersion: v1
  data:
    relay-init.sh: |
      echo "relay-init.sh"
      date
      if [[ -f /work/.relay/credentials.json ]]
      then
         echo "credentials already present."
      else
         echo "Generating credentials now"
         /bin/bash /docker-entrypoint.sh credentials generate
      fi
      sleep 1
      echo "done"
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name:  relay-init-command-script
kind: List
metadata: {}