kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "sentry.fullname" . }}-relay-credentials
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
{{- if (eq "-" .Values.relay.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.relay.persistence.storageClass }}"
{{- end }}
